---
- name: Remove default apache listeners
  lineinfile: dest=/etc/httpd/conf/httpd.conf state=present regexp='^Listen(.*)' line='#Listen\1' backrefs='yes'
- name: Set environment variables for apache
  template:
    src: sysconfig-httpd.j2
    dest: /etc/sysconfig/httpd
- name: Copy ssl config
  copy:
    src: ssl.conf
    dest: /etc/httpd/conf.d/ssl.conf
    mode: 0644
    owner: root
    group: root
  copy:
    src: 00ssl.include
    dest: /etc/httpd/conf.d/00ssl.include
    mode: 0644
    owner: root
    group: root
- name: Comment out the welcome conf
  command: sed -i "s/^[^#]/#&/" /etc/httpd/conf.d/welcome.conf
- name: Add vagrant user to apache group
  command: usermod -a -G apache vagrant
- name: Set permissions for /srv
  file: path=/srv owner=apache group=apache mode=0775 recurse=yes
- name: Run Apache httpd on boot
  service:
    name: httpd
    state: started
    enabled: yes
